CREATE TABLE IF NOT EXISTS customers (
   id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(50) UNIQUE,
   username VARCHAR(100) UNIQUE,
   phone_number VARCHAR(50) UNIQUE,
   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

   CONSTRAINT chk_customer_name_not_empty CHECK (length(trim(name)) > 0)
);

-- MOCK GENERATED BY CLAUDIOCODE; I DON'T KNOW THIS PERSONS
INSERT INTO customers (name, email, phone_number, username) VALUES
    ('Lucas Gómez', 'lucas.gomez@email.com', '+5491122334455', 'lucas_tattoo'),
    ('Sofía Rossi', 'sofia.rossi@email.com', '+5491133445566', 'sofi_art'),
    ('Mateo Fernández', 'mateo.f@email.com', '+5491144556677', NULL),
    ('Camila Benítez', 'cami.benitez@email.com', '+5491155667788', 'cami_b'),
    ('Valentín Torres', NULL, NULL, NULL),
    ('María Elena De La Cruz', 'maria.delacruz@domain.org', '+54 (11) 4567-8901', 'maria_elena'),
    ('Jean-Pierre Dupont', 'jp.dupont+test@sub.company.co.uk', '+33123456789', 'jp_dupont'),
    ('Gonzalo Pérez', 'gonzalo.p@gmail.com', '1144332211', 'gonzaperez_ok'),
    ('Íñigo Rodríguez', 'inigo@rodriguez.es', '+34600112233', 'inigo_rod'),
    ('Estudio Tattoo & Piercing S.A.', 'contacto@estudiotattoo.com', '+5491199887766', 'estudio_official');
