CREATE TABLE IF NOT EXISTS projects (
   id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   customer_id BIGINT NOT NULL,
   observations TEXT,
   images TEXT[] default '{}',
   "references" TEXT[] default '{}',
   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

   CONSTRAINT fk_project_customer
      FOREIGN KEY (customer_id)
      REFERENCES customers (id)
      ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_projects_customers_id ON projects(customer_id);

-- MOCK GENERATED BY CLAUDIOCODE; I DON'T KNOW WHAT ARE IN THESE IMAGES
INSERT INTO projects (customer_id, observations, images, "references") VALUES
    (1, 'Tatuaje manga completa estilo Neotradicional en brazo derecho.', ARRAY['https://storage.com/p1_img1.jpg', 'https://storage.com/p1_img2.jpg'], ARRAY['https://pinterest.com/ref1.jpg', 'https://pinterest.com/ref2.jpg']),
    (1, 'Cover-up en tobillo izquierdo.', '{}', '{}'),
    (2, 'Diseño de acuarela en la espalda, tonos fríos.', '{}', ARRAY['https://pinterest.com/watercolor1.jpg']),
    (3, NULL, ARRAY['https://storage.com/p4_stencil.jpg'], '{}'),
    (4, 'Primera idea para piercing en hélix.', '{}', '{}'),
    (6, 'Espalda completa estilo Oriental (Dragón y flores de cerezo).', ARRAY['https://storage.com/p6_lineart.jpg', 'https://storage.com/p6_shading.jpg'], ARRAY['https://pinterest.com/japan_ref1.jpg', 'https://pinterest.com/japan_ref2.jpg', 'https://pinterest.com/japan_ref3.jpg']),
    (7, 'Microrealismo de mascota en antebrazo.', ARRAY['https://storage.com/dog_photo.jpg'], ARRAY['https://storage.com/photo_edited.jpg']),
    (8, 'Diseño de letras finas (Fine Line) en costillas.', '{}', ARRAY['https://pinterest.com/font_ref.jpg']),
    (9, 'Pierna completa Blackwork.', ARRAY['https://storage.com/blackwork_session1.jpg'], ARRAY['https://pinterest.com/bw_ref.jpg']),
    (10, 'Consulta general para presupuesto de varios diseños.', '{}', '{}');
